enum ImageAsset {
    static let BboxxIcon = "BboxxIcon"
    static let startWithAppleButton = "startWithAppleButton"
    static let startWithGoogleButton = "startWithGoogleButton"
    static let startWithKakaoButton = "startWithKakaoButton"
    static let toolTip = "toolTip"
    static let emptyBoxIcon = "emptyBoxIcon"
    static let redoButton = "redoButton"
    static let bottomBackgroundBlock = "bottomBackgroundBlock"
    static let bottomBackgroundLine = "bottomBackgroundLine"
    static let bottomBackgroundMiddleLine = "bottomBackgroundMiddleLine"
    static let emptyingIcon = "emptyingIcon"
    static let main_feelingNote_character = "main_feelingNote_character"
    static let main_shouting_character = "main_shouting_character"
    static let timeMachineIcon = "timeMachineIcon"
    static let main_background_character = "main_background_character"
    static let main_all_background = "main_all_background"
    static let profileIcon = "profileIcon"
    static let main_down = "main_down"
    static let splash_logo = "splash_logo"
    static let splash_background1 = "splash_background1"
    static let splash_background2 = "splash_background2"
    
    static let micButton = "micButton"
    static let oneSeconds = "oneSeconds"
    static let twoSeconds = "twoSeconds"
    static let threeSeconds = "threeSeconds"
    
    static let leftSmallIcon = "leftSmallIcon"
    static let rightSmallIcon = "rightSmallIcon"
    
    static let trashIcon = "trashIcon"
    static let hugIcon = "hugIcon"
    static let writingIcon = "writingIcon"
    static let stoneIcon = "stoneIcon"
    static let main_empty_selection_backButton = "main_empty_selection_backButton"
    static let main_empty_selection_shouting = "main_empty_selection_shouting"
    static let main_empty_selection_feelingNote = "main_empty_selection_feelingNote"
    static let main_empty_selection_background = "main_empty_selection_background"
    static let main_empty_selection_full_background = "main_empty_selection_full_background"
    static let backButton = "backButton"
    static let closeButton = "closeButton"
}
